version: 1.1.{build}
pull_requests:
  do_not_increment_build_number: true
configuration: Release
platform: Any CPU
build:
  publish_nuget: true
  verbosity: minimal
deploy:
- provider: NuGet
  api_key:
    secure: 4lWivZ3z3d4Nb06zYDx8uyx+2b6iiH53U1evV6XaaMhNwzcHA3v13Bldgc5evKCw
notifications:
- provider: Email
  to:
  - jay@tdm.io
  subject: cslog - AppVeyor
  on_build_success: true
  on_build_failure: true
  on_build_status_changed: true